### ISSUE TITLE
Allow verifier to have something like `field: ['$exists' => true]`

### ISSUE THREAD

**Issue by amyboyd** [amyboyd/mongrate#5]
When a "up" migration needs to set a field to the current date/time, there is no way to verify this in the `verifier.yml`.

Possible workaround: allow YML to contain something like `date: $exists` or `date: [$exists: true]` ($exists like in MongoDB).

**Comment by BernardoSilva** [comment]
:+1:  nice feature to add.
`$exists` looks cleaner and simple.

**Comment by amyboyd** [comment]
Also 3rd option is something like `date: $instanceof MongoDate` -- this is stricter.

**Comment by amyboyd** [comment]
@thomasingram thoughts?

**Comment by thomasingram** [comment]
`$exists`
