### ISSUE TITLE
Make it BC compatible with symfony 2.3 long term supported version.

### ISSUE THREAD

**Issue by BernardoSilva** [amyboyd/mongrate#6]

**Comment by amyboyd** [comment]
The next LTS, 2.7, is released this month: http://symfony.com/doc/current/contributing/community/releases.html

2.3 is no longer an LTS in May 2016.

I think ensuring there is support for 2.7 is most important thing, but 2.3 is also somewhat important for another year.

**Comment by BernardoSilva** [comment]
My suggestion is to try make it BC compatible with `2.3` and  keep `1.x.x` and when `2.7` comes out if it requires breaking changes we bump the major release number to `2.0.0` so `mongrate` can also have a version supported until May 2016 `1.x.x` and a version using 2.7 `2.x.x`.
What you think?
